rootUrl: http://html.uplab.ru
gridUrl: http://127.0.0.1:4444/wd/hub

browsers:
#  ChromeIPhone5:
#    desiredCapabilities:
#      browserName: phantomjs
#      chromeOptions:
#        mobileEmulation:
#          userAgent: Mozilla/5.0 (iPhone; CPU iPhone OS 8_0 like Mac OS X) AppleWebKit/600.1.3 (KHTML, like Gecko) Version/8.0 Mobile/12A4345d Safari/600.1.4
#          deviceMetrics:
#            width: 320,
#            height: 568,
#            pixelRatio: 2

#  ChromeIPadHorizontal:
#    desiredCapabilities:
#      browserName: phantomjs
#      chromeOptions:
#        mobileEmulation:
#          userAgent: Mozilla/5.0 (iPad; CPU iPad OS 8_0 like Mac OS X) AppleWebKit/600.1.3 (KHTML, like Gecko) Version/8.0 Mobile/12A4345d Safari/600.1.4
#          deviceMetrics:
#            width: 1024,
#            height: 768,
#            pixelRatio: 2

  ChromeDesktop:
    windowSize: 1440x900
    desiredCapabilities:
      browserName: chrome
      #resolution: 1440x900
      acceptSslCerts: true

  IE:
    windowSize: 1440x900
    desiredCapabilities:
      browserName: internet explorer
      version: '11'
      os: 'Windows'
      os_version: '10'
      #resolution: 1440x900
      acceptSslCerts: true
      #ignoreProtectedModeSettings: true
      #ignoreZoomSetting: true
      #requireWindowFocus: true
      #ensureCleanSession: true

  Firefox:
     windowSize: 1440x900
     desiredCapabilities: 
      browserName: firefox
      version: ''
      #resolution: 1440x900
      acceptSslCerts: true

system:
  plugins:
    html-reporter/gemini:
      enabled: true
      path: gemini-reports
      defaultView: all

    json-reporter/gemini:
      enabled: true
      path: reports/report.json
 
compositeImage: true
